name: Test Reusable Action
on: push

jobs:
  test-reusable-action:
    runs-on: ubuntu-latest
    steps:
      - name: Call CodeQL Reusable Workflow
        uses: github-actions-course-nxbster/codeql-action@v0.1