#Test2
name: Test Reusable Action
on: push

jobs:
  #test-reusable-action:
    #permissions: write-all
    #uses: github-actions-course-nxbster/codeql-action/.github/workflows/codeql.yml@main

  test-composite-action:
    runs-on: ubuntu-latest
    name: Testing Composite Actions Workflow
    steps:
      - uses: github-actions-course-nxbster/codeql-action@main
        with:
          language: csharp